### ISSUE TITLE
PsN 4.9.0 installs PsNR@master by default, which lacks the only_libPaths option

### ISSUE THREAD

**Issue by rfaelens** [UUPharmacometrics/PsNR#3]
PsN 4.9.0 uses `R_info(directory=working.directory,only_libPaths=T)` in every R script.

Unfortunately, the PsNR version installed by setup.pl is the `@master` branch, where `only_libPaths` was removed in December through this commit: https://github.com/UUPharmacometrics/PsNR/commit/872febd46cbbe37b2c8121d74bc980209d638720

Please create a PsNR tag v4.9.0 that is compatible with the R-script templates in PsN 4.9.0, and update PsN to install this tag by default.

**Comment by rfaelens** [comment]
The most elegant workaround is probably to patch the following R script templates in PsN manually:
```
% grep -ir only_libPaths /usr/local/lib64/perl5/5.30.1/PsN_4_9_0
/usr/local/lib64/perl5/5.30.1/PsN_4_9_0/R-scripts/pvar_default.R:R_info(directory=working.directory,only_libPaths=T)
/usr/local/lib64/perl5/5.30.1/PsN_4_9_0/R-scripts/randtest_default.R:R_info(directory=working.directory,only_libPaths=T)
/usr/local/lib64/perl5/5.30.1/PsN_4_9_0/R-scripts/vpc_default.Rmd:R_info(directory=working.directory,only_libPaths=T)
/usr/local/lib64/perl5/5.30.1/PsN_4_9_0/R-scripts/sir_default.R:R_info(directory=working.directory,only_libPaths=T)
/usr/local/lib64/perl5/5.30.1/PsN_4_9_0/R-scripts/scm_default.Rmd:R_info(directory=working.directory,only_libPaths=T)
/usr/local/lib64/perl5/5.30.1/PsN_4_9_0/R-scripts/npfit_default.R:R_info(directory=working.directory,only_libPaths=T)
/usr/local/lib64/perl5/5.30.1/PsN_4_9_0/R-scripts/simeval_default.Rmd:R_info(directory=working.directory,only_libPaths=T)
/usr/local/lib64/perl5/5.30.1/PsN_4_9_0/R-scripts/llp_default.R:R_info(directory=working.directory,only_libPaths=T)
/usr/local/lib64/perl5/5.30.1/PsN_4_9_0/R-scripts/mcmp_default.R:R_info(directory=working.directory,only_libPaths=T)
/usr/local/lib64/perl5/5.30.1/PsN_4_9_0/R-scripts/execute_default.Rmd:R_info(directory=working.directory,only_libPaths=T)
/usr/local/lib64/perl5/5.30.1/PsN_4_9_0/R-scripts/improve_qa.R:R_info(directory=working.directory,only_libPaths=T)
/usr/local/lib64/perl5/5.30.1/PsN_4_9_0/R-scripts/sse_default.R:R_info(directory=working.directory,only_libPaths=T)
/usr/local/lib64/perl5/5.30.1/PsN_4_9_0/R-scripts/cdd_default.R:R_info(directory=working.directory,only_libPaths=T)
```
You can do that easily using `sudo sed -i.bak 's/,only_libPaths=T//' *.R *.Rmd`

I guess this is fixed in a newer version of PsN. Bug can be closed.

**Comment by rikardn** [comment]
Thanks for reporting this. This will be fixed in the next PsN version that will be released soon. We have an entirely new way of installing the R package and dependencies through the use of renv and frozen package versions for each release. This should make the installation much more robust. Admittedly the old scheme was too fragile.
