### ISSUE TITLE
PsNR error after execution 

### ISSUE THREAD

**Issue by Mutaz94** [UUPharmacometrics/PsNR#5]
I start getting this error after the PsN finish execution. A new pop-up window appears and it includes the following:

'''
Rscript.exe - Entry point is not found
the procedure entry point R_removeVarFromFrame could not be located in the dynamic link library PsNR
C:/PsN-5.0/Rlib/rlang/i386x/rlang.dll

''' 
This happened when I installed PsNR from GitHub with all dependencies 
Any thoughts?

**Comment by Mutaz94** [comment]
In addition to this error from inside R.
```
Error: package or namespace load failed for 'PsNR' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/PsN-5.0.0/Rlib/rlang/libs/i386/rlang.dll':
  LoadLibrary failure:  The specified procedure could not be found.
```

**Comment by rikardn** [comment]
I am not sure, but it could be an issue of having multiple R versions and compiling with one and running with the other.

If you are using PsN 5 on Windows you don't need to install PsNR manually since everything is bundled. Did you use the ```PsN-5.0.0-windows-64bit.zip``` when installing PsN?

**Comment by Mutaz94** [comment]
Yes. I did install the 64bit zip file from the website. Do you recommend Re-installation?

**Comment by rikardn** [comment]
If you used the windows zip you don't need to install PsNR manually from github. PsN is setup to use its bundled version of PsNR and its dependencies. These have been tested together. But i don't expect installing PsNR manually to do any harm. Did you change the psn.conf or install PsNR using the bundled R version?

**Comment by Mutaz94** [comment]
I installed PsNR when I tried to generate -rplots=1 after the execution, but it didn't work because PsNR is not installed. So I did install it manually. What should I do now?

**Comment by rikardn** [comment]
Since it is hard for me to understand what you did manually I would reinstall PsN 5 following the instructions for Windows here: https://uupharmacometrics.github.io/PsN/install.html

If you still get errors it might be easier to fault find from here.

**Comment by Mutaz94** [comment]
It worked well after re-installing PsN, and removing PsNR from R library on my device. Thank you!

**Comment by rikardn** [comment]
I am glad it works now!
